### ISSUE TITLE
Add a diagram aligned with the rest of the specs

### ISSUE THREAD

**Issue by dachafra** [kg-construct/fnml-spec#8]
As we agreed, all spec diagrams should look similar. Now a diagram is provided but it's not similar to the rest. 
I think the best way to do it is that @anaigmo will provide the figure and then @bjdmeest can add it to the spec

**Comment by anaigmo** [comment]
Hi! Here is the diagram aligned with the rest of the specs, the original is in `KGC CG-W3C (all)/Brainstormings/` with the rest. All the properties and things from TermMap aren't there because they already are in the core diagram. Please let me know if there are any errors or things missing. 

![RML-FnO](https://user-images.githubusercontent.com/36294992/208894912-c02d97d9-78b2-4656-a5b3-1be037fe8444.png)

**Comment by dachafra** [comment]
If there are no errors, I would suggest integrating this in the spec @bjdmeest @samiscoding
